// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzrdxaetoqhkfceoomgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cmR4YWV0b3Foa2ZjZW9vbWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDEwOTEsImV4cCI6MjA2MDI3NzA5MX0.h2X_BEshUrnJwm-w3oEvks3arRF-W-R7xpoHSApWgto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);